import { Glob } from "bun";
import * as path from "node:path";

const src = path.resolve(import.meta.dir, "..", "src");
const db = path.resolve(src, "db");
const modules = path.resolve(src, "modules");
const glob = new Glob("**/*.prisma");

function readFileContent(filePath: string) {
  return Bun.file(filePath).text();
}

let schema = `
// This schema file was generated by \`generate.ts\`
// Do not edit this file directly
`.trim();

const parts = (
  await Array.fromAsync(glob.scan({ cwd: db, absolute: true }))
).concat(await Array.fromAsync(glob.scan({ cwd: modules, absolute: true })));

for await (const filePath of parts) {
  schema += `// ${filePath.replace(src + "/", "")}
${await readFileContent(filePath)}`;
}

console.log(schema);
